"""
file_manager.py

Purpose:
    Centralize all file input/output operations.

Functions to implement:
    - read_transcript(filename)
        - Read transcript from transcripts folder
        - Return transcript text
    - save_transcript(filename, text)
        - Save transcript text generated by transcription.py
        - Ensure folder exists
    - save_summary(filename, text)
        - Save summary text to summaries folder
        - Ensure folder exists

Notes:
    - Optional: log file operations (read/write)
    - Keep all paths configurable via config.py
"""
