"""
file_manager.py

Purpose:
    Centralize all file input/output operations.

Functions to implement:
    - read_transcript(filename)
        - Read transcript from transcripts folder
        - Return transcript text
    - save_transcript(filename, text)
        - Save transcript text generated by transcription.py
        - Ensure folder exists
    - save_summary(filename, text)
        - Save summary text to summaries folder
        - Ensure folder exists

Notes:
    - Optional: log file operations (read/write)
    - Keep all paths configurable via config.py
"""

import os
from datetime import datetime
from .config import TRANSCRIPT_DIR

def generate_transcript_file():
    """
    Creates a new transcript file for each run using timestamp.
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"transcript_{timestamp}.txt"
    filepath = os.path.join(TRANSCRIPT_DIR, filename)
    
    # Create empty file
    open(filepath, "a", encoding="utf-8").close()
    return filepath

def append_text_to_file(filepath, text):
    """
    Appends a line of text to the specified file.
    """
    with open(filepath, "a", encoding="utf-8") as f:
        f.write(text + "\n")