import { NextRequest, NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth";
import prisma from "@/lib/db";

/**
 * GET /api/students/search?q=keyword
 * Search across transcriptions (summaries/reviewers), quizzes that the student has access to.
 * Performs case-insensitive partial matching on title, course, subject, and content.
 */
export async function GET(request: NextRequest) {
  try {
    const user = await getCurrentUser();

    if (!user) {
      return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
    }

    if (user.role !== "STUDENT") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 403 });
    }

    const student = await prisma.student.findUnique({
      where: { userId: user.userId },
    });

    if (!student) {
      return NextResponse.json({ error: "Student not found" }, { status: 404 });
    }

    const { searchParams } = new URL(request.url);
    const query = searchParams.get("q")?.trim();

    if (!query || query.length === 0) {
      return NextResponse.json({ results: [] });
    }

    // Get student's enrolled class IDs
    const enrollments = await prisma.studentClass.findMany({
      where: { studentId: student.id },
      select: { classId: true },
    });
    const enrolledClassIds = enrollments.map((e) => e.classId);

    // Search transcriptions (only from enrolled classes)
    // If student has no enrolled classes, return no transcription results
    const transcriptions = enrolledClassIds.length > 0
      ? await prisma.transcription.findMany({
          where: {
            status: "COMPLETED",
            classId: { in: enrolledClassIds },
            OR: [
              { title: { contains: query, mode: "insensitive" } },
              { course: { contains: query, mode: "insensitive" } },
              { content: { contains: query, mode: "insensitive" } },
            ],
          },
          select: {
            id: true,
            title: true,
            course: true,
            class: {
              select: {
                classCode: true,
                subject: true,
              },
            },
          },
          take: 5,
          orderBy: { createdAt: "desc" },
        })
      : [];

    // Search quizzes — only those generated by this student
    const quizzes = await prisma.quiz.findMany({
      where: {
        studentId: student.id,
        OR: [
          { lesson: { title: { contains: query, mode: "insensitive" } } },
          { lesson: { subject: { contains: query, mode: "insensitive" } } },
        ],
      },
      select: {
        id: true,
        type: true,
        difficulty: true,
        lesson: {
          select: {
            title: true,
            subject: true,
          },
        },
      },
      take: 5,
      orderBy: { createdAt: "desc" },
    });

    // Build unified results
    const results: Array<{
      id: string;
      type: string;
      title: string;
      subject: string;
      link: string;
    }> = [];

    // Map transcriptions → both "transcript" and "summary" entries
    for (const t of transcriptions) {
      const classCode = t.class?.classCode || "";
      const subject = t.class?.subject || t.course;

      // As a "summary" / reviewer
      results.push({
        id: `reviewer-${t.id}`,
        type: "summary",
        title: t.title,
        subject,
        link: classCode
          ? `/student/reviewers/${classCode}/${t.id}`
          : `/student/reviewers`,
      });

      // As a raw transcript
      results.push({
        id: `transcript-${t.id}`,
        type: "transcript",
        title: t.title,
        subject,
        link: classCode
          ? `/student/reviewers/transcripts/${classCode}/${t.id}`
          : `/student/reviewers`,
      });
    }

    // Map quizzes
    for (const q of quizzes) {
      results.push({
        id: `quiz-${q.id}`,
        type: "quiz",
        title: `${q.lesson.title} (${q.type})`,
        subject: q.lesson.subject,
        link: `/student/quizzes/${q.id}`,
      });
    }

    return NextResponse.json({ results });
  } catch (error) {
    console.error("Search error:", error);
    return NextResponse.json({ error: "Search failed" }, { status: 500 });
  }
}
